server:
  port: 8090
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lianyexin/compositeweb/             # 配置git仓库的地址
          search-paths: configRepo                                  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: lianyexin                                        # git仓库的账号
          password: chengda123                                       # git仓库的密码
  rabbitmq:
    host: 192.168.3.195
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/                  # 注册中心eurka地址


management:
  security:
     enabled: false