server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lianyexin/compositeweb              # 配置git仓库的地址
          search-paths: /**                                 # git仓库地址下的相对地址，可以配置多个，用,分割
          label: master                                              # 仓库分支
          username: lianyexin                                        # git仓库的账号
          password: chengda123                                       # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/